# ---------------------------------------------------------------------------------
#  Distributed under MIT Licence
#    See https://github.com/josephabbey/z7-coprocessor/blob/main/LICENCE.
# ---------------------------------------------------------------------------------

standard = "2008"
[libraries]
# xpm = { files = ["S:/Xilinx/Vivado/2023.2/data/vhdl/src/xpm/*.vhd"] }
ieee = { files = [
  "S:/Xilinx/Vivado/2023.2/data/vhdl/src/ieee_2008/*.vhdl",
], thirdparty = true }
